### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaMath/Grids.jl#3]
The goal of this package is to contain lightweight iterator objects for holding grids. Examples of functions that would create these types are `linspace`, `meshgrid`, and `ndgrid`. However, unlike the original MATLAB output as arrays, we should have proper implementations in Julia as lightweight types. This will allow for the grids to require only a small amount of memory but still naturally behave like the result of these functions. Here are some behaviors I think are crucial for this:

This continues a discussion currently seen at JuliaLang/julia#18492 and JuliaLang/julia#17408.
- Lightweight iterator types as the return values.
- The ability to `collect()` these results to arrays.
- Support for n-dimensional grids.
- Compatibility with units, a la [SIUnits.jl](https://github.com/Keno/SIUnits.jl) and [Unitful.jl](https://github.com/ajkeller34/Unitful.jl).
- Have not only an array interface, i.e. `x[i]` returns the `i`th grid value, but also a call interface `x(i)` (or `x[i]` on floats) which gives the value at intermediate points.

**Comment by ChrisRackauckas** [comment]
Note that this differs from Tim Holy's Grid.jl and Interpolations.jl as it's not for interpolating functions on grids, rather for creating lightweight objects which represent the grids themselves.

**Comment by timholy** [comment]
If you don't already know about it, `CartesianRange` and `CartesianIndex` might make a good backbone for iteration over grids. I think you just need a scaling factor and and offset, and then you're set (for regular rectangular grids).

**Comment by simonbyrne** [comment]
I think this could be very useful. Some other places which could make use of this:
* [`Histogram`s in StatsBase.jl]: https://github.com/JuliaStats/StatsBase.jl/blob/07109b62f90d2f7fc95ff2ea56c0812903417c39/src/hist.jl#L95-L104
* [https://github.com/JuliaStats/KernelDensity.jl]

**Comment by ChrisRackauckas** [comment]
I haven't gotten around to this, and it seems like it would be better fit for your new Ranges.jl and JuliaArrays (the idea I guess is n-dimensional linspaces). I think this discussion/issue should thus be closed and moved over there, with this package idea essentially being part of Ranges.jl.

 What do you think @timholy?

**Comment by DhruvaSambrani** [comment]
Do Boundary Conditions also fall in the scope of this package?
The archived Grid.jl, Interpolations.jl, DynamicGrids.jl all implement it, which could be simplified if we add it here

**Comment by ChrisRackauckas** [comment]
The code I was going to put in here is so old now that it would need to be completely rewritten, and BCs would make sense in the context of a package like DiffEqOperators. So I'm just going to delete this repo since I probably shouldn't've ever made it. The basic thing is to just stick two ranges in a type and lower indexing to them, the better thing is to do fancy Cartesian magic which I never updated it to do, so it's not worth sharing.
